AppCoder/urls.py
from django.urls import path
from AppCoder import views

app_name = 'AppCoder'

urlpatterns = [
    path('', views.inicio, name='Inicio'),
    path('cursos/', views.cursos, name='Cursos'),
    path('profesores/', views.profesores, name='Profesores'),
    path('estudiantes/', views.estudiantes, name='Estudiantes'),
    path('entregables/', views.entregables, name='Entregables'),
    #path('cursoformulario/', views.cursoformulario, name='CursoFormulario'),
    path('profesorFormulario/', views.profesorFormulario, name='ProfesorFormulario'),
    path('estudianteFormulario/', views.estudianteFormulario, name='EstudianteFormulario'),
    path('entregableFormulario/', views.entregableFormulario, name='EntregableFormulario'),
    path('busquedaCamada', views.busquedaCamada, name='BusquedaCamada'),
    path('buscar/', views.buscar),
]

ProyectoCoder/urls.py
from django.contrib import admin
from django.urls import path, include
from AppCoder.views import curso

app_name = 'AppCoder'

urlpatterns = [
    path('AppCoder/', include(('AppCoder.urls', 'AppCoder'), namespace='AppCoder')),
    path('admin/', admin.site.urls),
]

AppCoder/models.py
from django.db import models

# Create your models here.
class Curso(models.Model):
    nombre = models.CharField(max_length=40)
    camada = models.IntegerField()

class Estudiante(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField()

class Profesor(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    email = models.EmailField()
    profesion = models.CharField(max_length=30)

class Entregable(models.Model):
    nombre = models.CharField(max_length=30)
    fecha_entrega = models.DateField()
    entregado = models.BooleanField()

AppCoder/forms.py
from django import forms

class CursoFormulario(forms.Form):
    nombre = forms.CharField()
    camada = forms.IntegerField()

class ProfesorFormulario(forms.Form):
    nombre = forms.CharField()
    apellido = forms.CharField()
    email = forms.EmailField()
    profesion = forms.CharField()

class EstudianteFormulario(forms.Form):
    nombre = forms.CharField(max_length=30)
    apellido = forms.CharField(max_length=30)
    email = forms.EmailField()

class EntregableFormulario(forms.Form):
    nombre = forms.CharField(max_length=30)
    fecha_entrega = forms.DateField()
    entregado = forms.BooleanField()

AppCoder/views.py
from django.shortcuts import render
from AppCoder.models import Curso, Profesor, Estudiante, Entregable
from django.http import HttpResponse
from AppCoder.forms import CursoFormulario, ProfesorFormulario, EstudianteFormulario, EntregableFormulario

# Create your views here.
def curso(request):
    curso = Curso(nombre='Desarollo Web', camada='19881')
    curso.save()

    documentodetexto = f'---->Curso: {curso.nombre} Camdada: {curso.camada}'

    return HttpResponse(documentodetexto)

def inicio(request):
    return render(request, 'AppCoder/inicio.html')

def profesores(request):
    return render(request, 'AppCoder/profesores.html')

def entregables(request):
    return render(request, 'AppCoder/entregables.html')

def estudiantes(request):
    return render(request, 'AppCoder/estudiantes.html')

def cursos(request):
    if request.method == 'POST':
        miFormulario = CursoFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid():
            info = miFormulario.cleaned_data

            curso = Curso(nombre=info['nombre'], 
                          camada=info['camada'])
            curso.save()
            return render(request, 'AppCoder/inicio.html')
    else:
        miFormulario = CursoFormulario()

    return render(request, 'AppCoder/cursos.html', {'miFormulario': miFormulario})

def profesorFormulario(request):
    if request.method == 'POST':
        miFormulario = ProfesorFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid():
            info = miFormulario.cleaned_data
            profesor = Profesor(nombre=info['nombre'], 
                                apellido=info['apellido'],
                                email=info['email'],
                                profesion=info['profesion'])
            profesor.save()

            return render(request, 'AppCoder/inicio.html')
    else:
        miFormulario = ProfesorFormulario()

    return render(request, 'AppCoder/profesorFormulario.html', {'miFormulario': miFormulario})

def estudianteFormulario(request):
    if request.method == 'POST':
        miFormulario = EstudianteFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid():
            info = miFormulario.cleaned_data

            estudiante = Estudiante(nombre=info['nombre'], 
                                    apellido=info['apellido'],
                                    email=info['email'])
            estudiante.save()

            return render(request, 'AppCoder/inicio.html')
    else:
        miFormulario = EstudianteFormulario()

    return render(request, 'AppCoder/estudianteFormulario.html', {'miFormulario': miFormulario})

def entregableFormulario(request):
    if request.method == 'POST':
        miFormulario = EntregableFormulario(request.POST)
        print(miFormulario)

        if miFormulario.is_valid():
            info = miFormulario.cleaned_data

            entregable = Entregable(nombre=info['nombre'], 
                                    fecha_entrega=info['fecha_entrega'],
                                    entregado=info['entregado'])
            entregable.save()

            return render(request, 'AppCoder/inicio.html')
    else:
        miFormulario = EntregableFormulario()

    return render(request, 'AppCoder/entregableFormulario.html', {'miFormulario': miFormulario})

def busquedaCamada(request):
    return render(request, 'AppCoder/busquedaCamada.html')

def buscar(request):
    if request.GET['camada']:
        camada = request.GET['camada']
        curso = Curso.objects.filter(camada__icontains=camada)

        return render(request, 'AppCoder/inicio.html', {'cursos':curso, 'camada':camada})
    
    else:
        respuesta = 'No enviaste datos.'
    

    return HttpResponse(respuesta)

AppCoder/templates/AppCoder/busquedaCamada.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoquecambia %}
    {% if miFormulario.errors %}
    <p style="color: red;">Estan mal los datos, revisar.</p>
    {% endif %}

    <form action="/AppCoder/buscar/" method="GET">
        <input type="number" name="camada" id="camada">
        <input type="submit" value="buscar">
    </form>
    
{% endblock %}

AppCoder/templates/AppCoder/cursoformulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario - Agregar Curso</title>
</head>
<body>
    {% if miFormulario.errors %}
        <p style='color: red;'> Estan mal los datos, revisar</p>
    {% endif %}

    <form action="{% url 'AppCoder:CursoFormulario' %}" method="POST">{% csrf_token %}
        
        <!-- Aca van los elemento de Django-->
        
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">
    </form>
</body>
</html>

AppCoder/templates/AppCoder/cursos.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoquecambia %}

    <!-- En este lugar va lo que cambia y se asocia a la vista-->
    {% if miFormulario.errors %}
        <p style="color: red;">Estan mal los datos, revisar.</p>
    {% endif %}

    <form action="" method="POST">{% csrf_token %}
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit", value="Enviar"
    </form>
    
    <h1>Cursos</h1>
    <p>Aca va la infor de cursos</p>

{% endblock %}

AppCoder/templates/AppCoder/entregableFormulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario - Agregar Entregable</title>
</head>
<body>
    {% if miFormulario.errors %}
        <p style='color: red;'> Estan mal los datos, revisar</p>
    {% endif %}

    <form action="{% url 'AppCoder:EntregableFormulario' %}" method="POST">{% csrf_token %}
        
        <!-- Aca van los elemento de Django-->
        
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">
    </form>
</body>
</html>

AppCoder/templates/AppCoder/entregables.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoquecambia %}

    <!-- En este lugar va lo que cambia y se asocia a la vista-->
    <h1>Entregables</h1>
    <p>Aca va la info de entregables</p>

{% endblock %}

AppCoder/templates/AppCoder/estudianteFormulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario - Agregar Estudiante</title>
</head>
<body>
    {% if miFormulario.errors %}
        <p style='color: red;'> Estan mal los datos, revisar</p>
    {% endif %}

    <form action="{% url 'AppCoder:EstudianteFormulario' %}" method="POST">{% csrf_token %}
        
        <!-- Aca van los elemento de Django-->
        
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">
    </form>
</body>
</html>

AppCoder/templates/AppCoder/estudiantes.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoquecambia %}

    <!-- En este lugar va lo que cambia y se asocia a la vista-->
    <h1>Estudiantes</h1>
    <p>Aca va la info de estudiantes</p>

{% endblock %}

AppCoder/templates/AppCoder/inicio.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoquecambia %}
    <p>Estamos buscando el: {{camada}}</p>

    {% if curso %}
        <ul>
            {% for cur in curso %}
                <li> {{curso.nombre}} </li>
                <li> {{curso.camada}} </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

AppCoder/templates/AppCoder/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>ProyectoCoder - AppCoder</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'AppCoder/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'AppCoder:Inicio' %}">Home</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Cursos' %}">Cursos</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Profesores' %}">Profesores</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Estudiantes' %}">Estudiantes</a>
                <a class="navbar-brand" href="{% url 'AppCoder:Entregables' %}">Entregables</a>
                <a class="btn btn-primary" href="#signup">Iniciar</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Nuestra Web Intermedia de Django - CoderHouse</h1>
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form class="form-subscribe" id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <!-- Email address input-->
                                <div class="row">
                                    <div class="col">
                                        <input class="form-control form-control-lg" id="emailAddress" type="email" placeholder="Email Address" data-sb-validations="required,email" />
                                        <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:required">Email Address is required.</div>
                                        <div class="invalid-feedback text-white" data-sb-feedback="emailAddress:email">Email Address Email is not valid.</div>
                                    </div>
                                    <div class="col-auto"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
                                </div>
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        <p>To activate this form, sign up at</p>
                                        <a class="text-white" href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Esto es lo que cambia-->
        {% block contenidoquecambia %}

        {% endblock %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

AppCoder/templates/AppCoder/profesorFormulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario - Agregar Profesor</title>
</head>
<body>
    {% if miFormulario.errors %}
        <p style='color: red;'> Estan mal los datos, revisar</p>
    {% endif %}

    <form action="{% url 'AppCoder:ProfesorFormulario' %}" method="POST">{% csrf_token %}
        
        <!-- Aca van los elemento de Django-->
        
        <table>
            {{ miFormulario.as_table }}
        </table>

        <input type="submit" value="Enviar">
    </form>
</body>
</html>

AppCoder/templates/AppCoder/profesores.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoquecambia %}

    <!-- En este lugar va lo que cambia y se asocia a la vista-->
    <h1>Profesores</h1>
    <p>Aca va la info de profesores</p>

{% endblock %}

AppCoder/templates/AppCoder/resultadosBusqueda.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoquecambia %}
    <p>Estamos buscando el: {{camada}}</p>

    {% if curso %}
        <ul>
            {% for cur in curso %}
                <li> {{curso.nombre}} </li>
                <li> {{curso.camada}} </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}